[profile.default]
src = "src"
out = "out"
solc-version = "0.8.27"
env = ".env"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
